# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('process_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(verbose_name='蓝鲸项目ID')),
                ('order_type', models.CharField(max_length=255)),
                ('order_name', models.CharField(max_length=255)),
                ('ding_api', models.CharField(blank=True, max_length=1024, null=True)),
                ('ding_token', models.CharField(blank=True, max_length=1024, null=True)),
                ('process_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='process_config.ProcessConfig')),
            ],
            options={
                'db_table': 'order_center_order_config_order_config',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderconfig',
            unique_together=set([('biz_id', 'order_type')]),
        ),
    ]
