# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverorder',
            old_name='center_id',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='deliverorder',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='deliverorder',
            old_name='platform_id',
            new_name='platform',
        ),
    ]
