# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_auto_20200212_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorder',
            name='remark',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
