# -*- coding: utf-8 -*-


# 默认系统错误
EC_SYSTEM_ERROR = -1

# 蓝鲸组件接口错误
EC_BK_COMPONENT_API = -10

# 系统错误
EC_SERVER_500_ERROR = -101
EC_UNAUTHORIZED = -102
EC_PERMISSION_DENIED = -103
EC_METHOD_NOT_ALLOWED = -104
EC_OBJECT_NOT_EXIST = -105

# 请求正取返回
EC_OK = 0

# 通用逻辑错误
EC_COMMON_LOGIC_ERROR = 100

# 业务错误码
EC_PARAM_INCORRECT = 101
EC_VALIDATE_ERROR = 102
EC_COMPONENT_CALL = 103

EC_OPERATION_NOT_SUPPORTED = 104
