# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(verbose_name='业务ID')),
                ('machine', models.CharField(max_length=255, verbose_name='主机')),
                ('desc', models.CharField(max_length=255, verbose_name='描述')),
                ('work_dir', models.CharField(max_length=255, verbose_name='工作目录')),
                ('launch_user', models.CharField(max_length=1024, verbose_name='启动用户')),
                ('pid_path', models.CharField(max_length=1024, verbose_name='pid文件路径')),
                ('auto_restart', models.IntegerField(blank=True, default=0, verbose_name='是否自动拉起')),
                ('restart_interval', models.IntegerField(blank=True, default=60, verbose_name='拉起间隔')),
                ('operate_timeout', models.IntegerField(blank=True, default=600, verbose_name='操作超时时长')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(verbose_name='业务ID')),
                ('name', models.CharField(max_length=255, verbose_name='进程名')),
                ('conf_path', models.CharField(max_length=1024, verbose_name='配置文件路径')),
                ('start_cmd', models.CharField(max_length=1024, verbose_name='启动命令')),
                ('stop_cmd', models.CharField(max_length=1024, verbose_name='停止命令')),
                ('restart_cmd', models.CharField(max_length=1024, verbose_name='重启命令')),
                ('reload_cmd', models.CharField(max_length=1024, verbose_name='重载命令')),
                ('pack_name', models.CharField(max_length=255, verbose_name='程序包名')),
                ('template',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_center.ConfigTemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manage.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('biz_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([('biz_id', 'process', 'machine', 'work_dir')]),
        ),
    ]
