# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(default=0)),
                ('config_key', models.CharField(max_length=64, null=True)),
                ('config_value', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together=set([('biz_id', 'config_key')]),
        ),
    ]
