# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('order_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApprovalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor', models.CharField(max_length=255)),
                ('approval_step', models.IntegerField()),
                ('approval_step_result', models.IntegerField()),
                ('approval_step_remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('task_instance_id', models.IntegerField(default=0)),
                ('jobs_state', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_response', models.TextField(default='{}')),
            ],
            options={
                'db_table': 'order_center_order_order_approval_record',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=255)),
                ('biz_id', models.IntegerField()),
                ('suborder', models.IntegerField()),
                ('order_state', models.IntegerField(default=1)),
                ('current_approval_step', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_type_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                                    to='order_config.OrderConfig')),
            ],
            options={
                'db_table': 'order_center_order_orders',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderapprovalrecord',
            name='order_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='order.Orders'),
        ),
    ]
