# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderapprovalrecord',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_type_id',
            new_name='order_config',
        ),
    ]
