# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 17:19
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
                ('params', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='NotifyRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('types', jsonfield.fields.JSONField(default=dict)),
                ('tags', jsonfield.fields.JSONField(default=dict)),
                ('destination', models.ManyToManyField(to='notify_manage.Channel')),
            ],
        ),
    ]
