# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0013_domainmodel_cdn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='集群名')),
                ('bk_biz', models.IntegerField(verbose_name='项目ID')),
                ('hosts', models.CharField(default='[]', max_length=256, verbose_name='集群主机')),
                ('package', models.CharField(max_length=255, verbose_name='程序包名')),
            ],
            options={
                'verbose_name': '集群管理',
                'verbose_name_plural': '集群管理',
            },
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='配置名')),
                ('bk_biz', models.IntegerField(default=3, verbose_name='业务ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.CertModel', verbose_name='证书')),
            ],
            options={
                'verbose_name': '配置管理',
                'verbose_name_plural': '配置管理',
            },
        ),
        migrations.CreateModel(
            name='VhostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz', models.IntegerField(default=3, verbose_name='业务ID')),
                ('port', models.IntegerField(default=443, verbose_name='端口')),
                ('ssl', models.BooleanField(default=True, verbose_name='开启ssl')),
                ('root', models.CharField(default='html', max_length=256, verbose_name='默认root')),
                ('index', models.CharField(default='index.html index.htm', max_length=64, verbose_name='默认index')),
                ('content', models.TextField(verbose_name='内容')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nginx.ConfigModel', verbose_name='配置')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.DomainModel', verbose_name='域名')),
            ],
            options={
                'verbose_name': '虚拟主机',
                'verbose_name_plural': '虚拟主机',
            },
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nginx.ConfigModel', verbose_name='配置'),
        ),
    ]
