# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustermodel',
            name='bk_biz',
            field=models.IntegerField(default=3, verbose_name='项目ID'),
        ),
        migrations.AlterField(
            model_name='vhostmodel',
            name='ssl',
            field=models.BooleanField(default=False, verbose_name='开启ssl'),
        ),
    ]
