# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0002_auto_20200604_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustermodel',
            name='path',
            field=models.CharField(default='/data/app/openresty-moonton/', max_length=128, verbose_name='工作路径'),
        ),
    ]
