# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 16:21
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4)),
                ('bk_biz', models.IntegerField(verbose_name='蓝鲸项目ID')),
                ('module', models.CharField(choices=[('default', 'default')], default='default', max_length=32,
                                            verbose_name='模块')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('exec_ip', models.TextField(default='[]', verbose_name='执行地址')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='作业账户')),
                ('script', models.TextField(blank=True, null=True, verbose_name='脚本')),
                ('script_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='脚本名')),
                ('callback', models.CharField(blank=True, max_length=512, null=True, verbose_name='回调地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作业管理',
                'verbose_name_plural': '作业管理',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskInstanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.IntegerField(unique=True, verbose_name='实例')),
                ('name', models.CharField(max_length=128, verbose_name='任务名')),
                ('user', models.CharField(max_length=64, verbose_name='启动人')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('status', models.IntegerField(default=-1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('total_time', models.IntegerField(default=0, verbose_name='总耗时')),
                ('result_log', models.TextField(blank=True, null=True, verbose_name='返回结果')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.JobModel',
                                          verbose_name='作业ID')),
            ],
            options={
                'verbose_name': '任务实例',
                'verbose_name_plural': '任务实例',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobmodel',
            unique_together=set([('bk_biz', 'job_uuid')]),
        ),
    ]
