# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseOrder',
            fields=[
                ('release_id', models.AutoField(primary_key=True, serialize=False, verbose_name='发布id')),
                ('env', models.CharField(default='阿里云', max_length=50, verbose_name='发布环境')),
                ('release_version', models.CharField(max_length=50, verbose_name='发布版本号')),
                ('svn_version', models.IntegerField(verbose_name='svn版本号')),
                ('release_flag', models.CharField(default='0:0', max_length=50, verbose_name='发布标志')),
                ('state', models.IntegerField(default=1, verbose_name='状态')),
                ('enable', models.IntegerField(default=1, verbose_name='是否启用')),
                ('contact_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='内容提供人')),
                ('desc', models.CharField(default='无', max_length=255, verbose_name='描述说明')),
                ('reason', models.CharField(max_length=255, verbose_name='原因')),
                ('level', models.IntegerField(default=0, verbose_name='优先等级')),
                ('servers', models.CharField(max_length=500, verbose_name='服务')),
                ('server_list', models.TextField(verbose_name='服务列表')),
                ('remark', models.TextField(default='无', verbose_name='备注/特殊说明')),
            ],
            options={
                'verbose_name': '发布申请',
                'verbose_name_plural': '发布申请',
                'db_table': 'order_center_release_release_order',
            },
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('app', models.CharField(max_length=64, verbose_name='应用')),
                ('server', models.CharField(max_length=64, verbose_name='服务')),
                ('division', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='分区')),
                ('node', models.CharField(max_length=64, verbose_name='节点')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('use_agent', models.IntegerField(verbose_name='代理')),
            ],
            options={
                'verbose_name': 'Server管理',
                'verbose_name_plural': 'Server管理',
                'db_table': 't_server',
            },
        ),
        migrations.AlterUniqueTogether(
            name='servermodel',
            unique_together=set([('app', 'server', 'division', 'node')]),
        ),
    ]
