# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-09 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
    ]
