# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(default=0, verbose_name='业务ID')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
                ('users', models.TextField(default='[]', verbose_name='用户列表')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(default=0, verbose_name='业务ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名')),
                ('routes', models.TextField(default='[]', verbose_name='路由列表')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('group', models.ManyToManyField(to='permission.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '角色授权',
                'verbose_name_plural': '角色授权',
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('biz_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('biz_id', 'name')]),
        ),
    ]
