# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255, unique=True)),
                ('state', models.IntegerField(default=0)),
                ('biz_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'deliver_manage_center',
            },
        ),
        migrations.CreateModel(
            name='ClearanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_host_id', models.IntegerField()),
                ('biz_id', models.IntegerField()),
                ('remove_id', models.CharField(max_length=255)),
                ('bk_host_innerip', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_host_outerip', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_host_outerip_2', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('disk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('server_city', models.CharField(blank=True, max_length=255, null=True)),
                ('bandwidth', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('server_country', models.CharField(blank=True, max_length=255, null=True)),
                ('sl_account', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_host_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_os_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_os_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_os_bit', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_cpu', models.IntegerField()),
                ('bk_cpu_mhz', models.IntegerField()),
                ('bk_cpu_module', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_mem', models.IntegerField()),
                ('bk_disk', models.IntegerField()),
                ('bk_mac', models.CharField(blank=True, max_length=255, null=True)),
                ('bk_outer_mac', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.CharField(blank=True, max_length=255, null=True)),
                ('clearance_flag', models.IntegerField(default=1)),
                ('clearance_create_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                               on_delete=django.db.models.deletion.DO_NOTHING, to='order.Orders')),
            ],
            options={
                'db_table': 'deliver_manage_clearance_detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeliverDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(default=0)),
                ('bk_host_innerip', models.CharField(max_length=255)),
                ('bk_host_outerip', models.CharField(max_length=255)),
                ('bk_comment', models.CharField(max_length=255)),
                ('bk_host_outerip_2', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('disk_type', models.CharField(max_length=255)),
                ('server_city', models.CharField(max_length=255)),
                ('bandwidth', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('server_country', models.CharField(max_length=255)),
                ('sl_account', models.CharField(max_length=255)),
                ('ssh_ip', models.CharField(max_length=255)),
                ('isp', models.CharField(max_length=255)),
                ('bk_host_name', models.CharField(max_length=255)),
                ('bk_os_type', models.CharField(max_length=255)),
                ('bk_os_name', models.CharField(max_length=255)),
                ('bk_os_version', models.CharField(max_length=255)),
                ('bk_os_bit', models.CharField(max_length=255)),
                ('bk_cpu', models.IntegerField()),
                ('bk_cpu_mhz', models.IntegerField()),
                ('bk_cpu_module', models.CharField(max_length=255)),
                ('bk_mem', models.IntegerField()),
                ('bk_disk', models.IntegerField()),
                ('bk_mac', models.CharField(max_length=255)),
                ('bk_outer_mac', models.CharField(max_length=255)),
                ('detail_flag', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                               to='order.Orders')),
            ],
            options={
                'db_table': 'deliver_manage_deliver_detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255, unique=True)),
                ('cpu', models.CharField(max_length=255)),
                ('mem', models.CharField(max_length=255)),
                ('sdisk', models.CharField(max_length=255)),
                ('disk', models.CharField(blank=True, max_length=255, null=True)),
                ('ssd', models.CharField(blank=True, max_length=255, null=True)),
                ('net', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(max_length=255)),
                ('state', models.IntegerField(default=0)),
                ('biz_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'deliver_manage_host',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=255)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('passwd', models.CharField(blank=True, max_length=255, null=True)),
                ('biz_id', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'deliver_manage_platform',
            },
        ),
        migrations.CreateModel(
            name='PlatformCenterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'deliver_manage_platform_center_map',
            },
        ),
        migrations.CreateModel(
            name='PlatformHostProfileMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('hid', models.IntegerField()),
            ],
            options={
                'db_table': 'deliver_manage_platform_host_map',
            },
        ),
        migrations.AlterUniqueTogether(
            name='platformhostprofilemap',
            unique_together=set([('pid', 'hid')]),
        ),
        migrations.AlterUniqueTogether(
            name='platformcentermap',
            unique_together=set([('pid', 'cid')]),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set([('platform_name', 'biz_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='clearancedetail',
            unique_together=set([('biz_id', 'bk_host_id', 'remove_id')]),
        ),
    ]
