# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
        ('deliver_manage', '0002_auto_20200211_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverdetail',
            unique_together=set([('biz_id', 'order_id', 'bk_host_innerip')]),
        ),
    ]
