# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
        ('deliver_manage', '0003_auto_20200212_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='deliverdetail',
            unique_together=set([('biz_id', 'order', 'bk_host_innerip')]),
        ),
    ]
