# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('deliver_manage', '0004_auto_20200212_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancedetail',
            name='bk_cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearancedetail',
            name='bk_cpu_mhz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearancedetail',
            name='bk_disk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearancedetail',
            name='bk_mem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
