# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64, unique=True, verbose_name='域名')),
                ('san_domain', models.CharField(max_length=64, verbose_name='附加域名')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('expired_time', models.DateTimeField(verbose_name='过期时间')),
                ('ca', models.TextField(blank=True, null=True, verbose_name='CA证书')),
                ('crt', models.TextField(verbose_name='证书文件')),
                ('key', models.TextField(verbose_name='证书秘钥')),
            ],
            options={
                'verbose_name': '证书管理',
                'verbose_name_plural': '证书管理',
            },
        ),
        migrations.CreateModel(
            name='CertRegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64, unique=True, verbose_name='域名')),
                ('san_domain', models.CharField(default='no', max_length=64, verbose_name='附加域名')),
                ('status', models.IntegerField(choices=[(0, '完成'), (1, '创建'), (2, '更新')], default=1, verbose_name='状态')),
                ('instance', models.IntegerField(unique=True, verbose_name='实例')),
                ('bk_biz', models.IntegerField(default=4, verbose_name='业务ID')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '证书注册',
                'verbose_name_plural': '证书注册',
            },
        ),
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='集群名')),
                ('bk_biz', models.IntegerField(verbose_name='项目ID')),
                ('hosts', models.CharField(default='127.0.0.1', max_length=256, verbose_name='集群主机')),
                ('path', models.CharField(max_length=64, verbose_name='证书路径')),
                ('script', models.CharField(blank=True, max_length=256, null=True, verbose_name='服务器管理')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.CertModel', verbose_name='证书')),
            ],
            options={
                'verbose_name': '集群管理',
                'verbose_name_plural': '集群管理',
            },
        ),
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='域名')),
                ('bk_biz', models.IntegerField(default=3, verbose_name='业务ID')),
                ('check_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='检查时间')),
                ('create_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间')),
                ('expired_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '域名管理',
                'verbose_name_plural': '域名管理',
            },
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.DomainModel', verbose_name='域名'),
        ),
    ]
