# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certmodel',
            name='san_domain',
        ),
        migrations.RemoveField(
            model_name='certregistermodel',
            name='san_domain',
        ),
        migrations.AddField(
            model_name='certregistermodel',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='名字'),
        ),
    ]
