# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20200218_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certregistermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='certmodel',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='名字'),
        ),
    ]
