# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_auto_20200218_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustermodel',
            name='hosts',
            field=models.CharField(default='[]', max_length=256, verbose_name='集群主机'),
        ),
    ]
