# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20200222_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='certmodel',
            name='bk_biz',
            field=models.IntegerField(default=3, verbose_name='业务ID'),
        ),
    ]
