# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_certmodel_bk_biz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz', models.IntegerField(default=3, verbose_name='业务ID')),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
                ('key', models.CharField(max_length=128, verbose_name='Key')),
                ('secert', models.CharField(max_length=128, verbose_name='Secert')),
                ('account', models.TextField(blank=True, null=True, verbose_name='Account_Key')),
            ],
            options={
                'verbose_name': '账户管理',
                'verbose_name_plural': '账户管理',
            },
        ),
        migrations.AlterField(
            model_name='certmodel',
            name='domain',
            field=models.CharField(max_length=128, unique=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='certmodel',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='名字'),
        ),
    ]
