# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_auto_20200224_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certmodel',
            name='bk_biz',
        ),
        migrations.AddField(
            model_name='certmodel',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='certificate.AccountModel', verbose_name='账户'),
            preserve_default=False,
        ),
    ]
