# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_auto_20200224_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertRegisterModel',
        ),
    ]
