# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_delete_certregistermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certmodel',
            name='domain',
            field=models.CharField(max_length=128, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='domainmodel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='域名'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmodel',
            unique_together=set([('bk_biz', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='certmodel',
            unique_together=set([('account', 'domain')]),
        ),
        migrations.AlterUniqueTogether(
            name='clustermodel',
            unique_together=set([('bk_biz', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='domainmodel',
            unique_together=set([('bk_biz', 'name')]),
        ),
    ]
