# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0011_remove_certmodel_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
        migrations.AddField(
            model_name='certmodel',
            name='bk_biz',
            field=models.IntegerField(default=3, verbose_name='业务ID'),
        ),
        migrations.AlterUniqueTogether(
            name='certmodel',
            unique_together=set([('bk_biz', 'domain')]),
        ),
    ]
