# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0012_auto_20200303_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainmodel',
            name='cdn',
            field=models.BooleanField(default=False, verbose_name='CDN'),
        ),
    ]
