# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('step_name', models.CharField(blank=True, default=None, max_length=255)),
                ('auditor', models.CharField(blank=True, default=None, max_length=2048)),
                ('step_flag', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, default=None, max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('task_flag', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'order_center_process_config_approval_flow',
            },
        ),
        migrations.CreateModel(
            name='ProcessConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(verbose_name='蓝鲸项目ID')),
                ('process_type', models.CharField(max_length=255)),
                ('process_name', models.CharField(max_length=255)),
                ('process_steps', models.IntegerField()),
            ],
            options={
                'db_table': 'order_center_process_config_process_config',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='processconfig',
            unique_together=set([('biz_id', 'process_type')]),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='process_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='process_config.ProcessConfig'),
        ),
    ]
