# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('process_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalflow',
            old_name='process_id',
            new_name='process',
        ),
    ]
