# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process_config', '0002_auto_20200212_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='audit_type',
            field=models.IntegerField(choices=[(1, '用户'), (2, '用户组')], default=1),
        ),
    ]
