# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_config', '0003_approvalflow_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='notify_flag',
            field=models.IntegerField(default=0),
        ),
    ]
