# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(verbose_name='业务ID')),
                ('key', models.CharField(max_length=255, verbose_name='配置项')),
                ('value', models.TextField(verbose_name='配置值')),
            ],
            options={
                'verbose_name': '配置项',
                'verbose_name_plural': '配置项',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.IntegerField(default=0, verbose_name='业务ID')),
                ('name', models.CharField(max_length=50, verbose_name='模板名')),
                ('desc', models.TextField(verbose_name='描述')),
                ('content', models.TextField(verbose_name='模板内容')),
            ],
            options={
                'verbose_name': '配置模板',
                'verbose_name_plural': '配置模板',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='configtemplate',
            unique_together=set([('biz_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='configkv',
            unique_together=set([('biz_id', 'key')]),
        ),
    ]
